name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "."  # Path to your code
          target: ${{ secrets.TARGET_DIR }}  # Path on the EC2 instance

      - name: Execute Bash Script
        run: |
          # Add your bash script command here
          # For example, running a script named "deploy.sh"
          chmod +x deploy.sh
          ./deploy.sh

